name: "Bug report"
description: "Report something that isn't working in Baller"
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue! Please fill this out with as much detail as possible.
        Tip: Screenshots, short videos, and console logs make fixes much faster.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: Briefly describe the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps so we can reproduce it reliably.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Enter ...
        4. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Describe the expected result.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: Describe the actual result, including error messages if any.
    validations:
      required: true

  - type: textarea
    id: media
    attributes:
      label: Screenshots / videos
      description: Drag and drop images/videos here, or paste links.
      placeholder: Add screenshots, screen recordings, or links.

  - type: textarea
    id: logs
    attributes:
      label: Console logs / errors
      description: Paste relevant logs (browser console, server logs, etc.).
      render: shell
      placeholder: Paste logs here.

  - type: dropdown
    id: affected_area
    attributes:
      label: Affected area
      description: Where is the bug happening?
      options:
        - Home page
        - Dashboard
        - Login / Signup
        - Listing parsing / Model output
        - Uploads / Media handling
        - Performance / Timeouts
        - Other
    validations:
      required: true

  - type: input
    id: listing_url
    attributes:
      label: Listing URL (if relevant)
      description: If the bug involves parsing a listing, paste the URL here.
      placeholder: https://...

  - type: input
    id: browser
    attributes:
      label: Browser (if applicable)
      description: Example: Chrome 121, Safari 17, Firefox 122
      placeholder: "Chrome 121"

  - type: input
    id: device
    attributes:
      label: Device / OS
      description: Example: Windows 11, macOS 14, iPhone iOS 17
      placeholder: "Windows 11"

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Anything else that might help us debug (frequency, workarounds, related issues).
      placeholder: Add any extra details here.